# Generated by Django 4.2.4 on 2023-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_img',
            field=models.ImageField(upload_to='', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='email',
            field=models.EmailField(max_length=55, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phone',
            field=models.IntegerField(max_length=11, verbose_name='Номер телефона'),
        ),
    ]
