# Generated by Django 4.2.4 on 2023-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employees_emp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_img',
            field=models.ImageField(upload_to='OlimpiadaDjango/files/images/', verbose_name='Фото сотрудника'),
        ),
    ]
